apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vtuq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/my-app/devfile-sample-vtuq@sha256:4391e5a684fd2beb3c9f2171a926d96f586936f469c3b7b5ef2a2d8c1f9917ba
        name: my-nodejs
        resources: {}
status: {}
